---
title: "Day Eleven: Ethnographies of Infrastructure"
subtitle: "SDS 237: Data Ethnography"
author: |
  Lindsay Poirier<br/>
  <span style = 'font-size: 70%;'>
  [Statistical & Data Sciences](http://www.smith.edu/sds), Smith College<br/>
  </span>
date: |
  Fall 2023<br/>
  `r sds::img_logo(width = 64)`
format: 
  revealjs:
    scrollable: true
    df-print: paged
    theme: [default]
    incremental: true
    chalkboard:
      theme: whiteboard
      boardmarker-width: 5
editor: source
execute:
  echo: true
  messages: false
  warnings: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```



# Select a favorite dataset. Brainstorm a long list of infrastructures that support that dataset. 

---

## Turn to your neighbor and discuss:

Pick one supporting infrastructure: 

- How often do you think about this infrastructure? Did you notice it pre-breakdown?
- Who has a say in the design of this infrastructure, and who is excluded?

---

# Why does Star consider infrastructure *relational*?

---

## Relationality of Infrastructure

> infrastructue is a fundamentally relational concept, becoming real infrastructure in relation to organized practice.

- Often we think of infrastructure as "just there"
- Assumes that infrastructure is the same thing for all people all of the time
- Viewing infrastructure as "relational" acknowledges that certain things *become* infrastructure to different people in different moments
- Not so much "what is infrastructure" but "when is infrastructure"

---

# Select one infratucture. How relational? How does it meet the other criteria of infrastructure?

---

## Star's Definition of Infrastructure

- Embeddedness: Sunk into other socio-technical structures
- Transparency: Does not need to continuously be reassembled
- Reach or Scope: Connects more than one site
- Learned as part of membership: Use naturalized through communities of practice
- Embodiment of standards: Component parts can connect through standardized conventions
- Built on an installed base: Wrestles with the logics of its underlying infrastructures
- Visible upon breakdown: Often taken for granted until breaking

---

## Master Narratives

- Singular voice designed into infrastructures that do not attend to diversity
- Assumed to speak for everyone
- Identifying involves asking: what has been made other by the design of this infrastructure?

---

## Invisible Work

- Work that fades into the background when presenting an infrastructure
- Sometimes invisible because that work is "tacit" or rote
- Sometimes structurally hidden from view
- Identifying involves asking: what forms of labor tend to go unrecognized when looking at this infrastructure

---

## Bringing an Ethnographic Sensibility to Archives

> Switch slide deck if there is time...

---



