---
title: "Day Twelve: Classification"
subtitle: "SDS 237: Data Ethnography"
author: |
  Lindsay Poirier<br/>
  <span style = 'font-size: 70%;'>
  [Statistical & Data Sciences](http://www.smith.edu/sds), Smith College<br/>
  </span>
date: |
  Spring 2023<br/>
  `r sds::img_logo(width = 64)`
format: 
  revealjs:
    scrollable: true
    df-print: paged
    theme: [default]
    incremental: true
    chalkboard:
      theme: whiteboard
      boardmarker-width: 5
editor: source
execute:
  echo: true
  messages: false
  warnings: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```


## Identify a classification system that structures some aspect of your "work". How are concepts organized in this classification system?

---

## Turn to your neighbor and discuss:

- What is the master narrative running through this classification system?

---

# What were some of the takeaways from Thursday?

---

# In what ways are classification systems examples of "infrastructure" according to Star?

---

## Datasets that rely on the ICD

- Navigate to [data.gov](data.gov) and search for "ICD"
- How do these datasets rely on the ICD?

---

# Reading Discussion

---

# What is the <ins>master narrative</ins> of the ICD?

---

# What <ins>invisible work</ins> shapes the ICD?

---

# How can we study the ICD?

---

# sameAs

---

# Archives of U.S. Federal Racial/Ethnic Classifications

---

## Mini-Project 1

- Due October 26 (in 2 weeks)
- Choice between a discourse analysis or a cultural analysis of infrastructure
- Both involve practicing the **methods** we have discussed in class
- Both involve producing an **argument** from ethnographic evidence
- Argument should be *descriptive*, not of *value* or *policy*
- Video describing both projects in depth is available on Perusall


