---
title: "Day Twenty-One: Data Activism"
subtitle: "SDS 237: Data Ethnography"
author: |
  Lindsay Poirier<br/>
  <span style = 'font-size: 70%;'>
  [Statistical & Data Sciences](http://www.smith.edu/sds), Smith College<br/>
  </span>
date: |
  Fall 2023<br/>
  `r sds::img_logo(width = 64)`
format: 
  revealjs:
    scrollable: true
    df-print: paged
    theme: [default]
    incremental: true
    chalkboard:
      theme: whiteboard
      boardmarker-width: 5
editor: source
execute:
  echo: true
  messages: false
  warnings: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```



## Consider a time when you felt surveiled, misrespresented, or under-represented by a data system. How did you respond?

---

## Turn to a neighbor and discuss:

- What do you suppose the designers of this system believe about the data it's collecting?
- What would it look like to resist this system?

---

# Reading Discussion


---

## Social Movement Theory

- Sociological research that studies how social movements form, operate, sustain, and fizzle out
- Political Process Theory: suggests that certain political formations enable social movements to form and operate
  - Political opportunities
  - Mobilizing structures
  - Framing processes
  - Protest cycles
  - Repertoires of contention
- Resource Mobilization Theory: suggests that the ability to leverage certain resources enable social movements to mobilize
  - Materials resources, human resources, organizational resources, cultural resources, etc.

---

## Data Activism

- A range of practices that confront the politics of datafication
- May involve affirmative data action
- May involve resistance to data systems


---


<iframe width="560" height="315" src="https://www.youtube.com/embed/LnIklqHkixE?si=k1r1tSLFlzC4xH7i" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>


---

<iframe width="560" height="315" src="https://www.youtube.com/embed/Ph6kT34bh-k?si=3HDf42OaN90Og7Zv" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>


---

<iframe width="560" height="315" src="https://www.youtube.com/embed/nMfPEbNBA-k?si=LeRCg754p-dlUdGy" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

---

<iframe width="560" height="315" src="https://www.youtube.com/embed/xWhGp5WauY8?si=ebWMaQMaSfX99E8e&amp;start=492" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>


