---
title: "Day Eight: Research Ethics"
subtitle: "SDS 237: Data Ethnography"
author: |
  Lindsay Poirier<br/>
  <span style = 'font-size: 70%;'>
  [Statistical & Data Sciences](http://www.smith.edu/sds), Smith College<br/>
  </span>
date: |
  Spring 2023<br/>
  `r sds::img_logo(width = 64)`
format: 
  revealjs:
    scrollable: true
    df-print: paged
    theme: [default]
    incremental: true
    chalkboard:
      theme: whiteboard
      boardmarker-width: 5
editor: source
execute:
  echo: true
  messages: false
  warnings: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

## Free-write for the next 2 minutes: You've submitted your first assignment - both individual and group. What have you learned so far that's sticking with you the most? What questions do you have about course infrastructure? What challenges have you run into?

---

## I encourage you to come to office hours if...

- You'd like to discuss strategies for managing the reading/workload.
- You'd like clarifications on any of the assignment expectations/course infrastructure.
- You'd like to review certain concepts discussed in lecture or the readings.
- You'd like to chat about opportunities for exploring more about data ethnography. 
- You're stressed and need some positive affirmation. 

---

# What were some takeaways from Thursday's class?

---

## Common Rule

- In the US, research organizations receiving federal funding are subject to the Common Rule
  - Laws and regulations regarding how Institutional Review Boards are to operate
  - IRBs are organizational bodies that review the ethics of human subjects research in order to protect human welfare, rights, and privacy before a study gets carried out
- Usually composed of representatives from an institution with a diverse background

---

## Tuskegee Study

- Conducted from 1932 to 1972 by US Public Health Services and Center for Disease Control, in collaboration with Tuskegee University in Alabama
- Involved 400 African Americans with syphilis 
- Study of leaving the disease untreated even though it was treatable
  - Were told they would receive free medical care
  - Never informed of their diagnosis
  - Provided with placebos and ineffective methods

---

## Facebook’s Emotional Contagion Study

- January 2012, Facebook data scientists manipulated what 700,000 users saw on feeds to examine emotional contagion
  - Some shown happy, positive content
  - Others shown sad, negative content
- Legal?
- Ethical?

---

## Ethics of ethnographic research

- Ethnography different than many other forms of human subjects research in that it takes place in natural settings vs in clinical settings
- Question of how to balance benefits of the research with the potential harms posed to the participants
- Potential harms:
  - Reputation
  - Disclosure of personal information
  - Disruption of relationships
  - Loss of claims
  
---

# What about informed consent in virtual spaces?

---

# Dataset Review in Project Groups



